AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 900
Outputs:
  HelloFunction:
    Value: !GetAtt HelloFunction.Arn
  WorldFunction:
    Value: !GetAtt WorldFunction.Arn
Resources:
  HelloFunction:
    Properties:
      CodeUri: hello/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.8
    Type: AWS::Serverless::Function
  WorldFunction:
    Properties:
      CodeUri: world/
      Handler: app.lambda_handler
      Policies:
        - AmazonSQSFullAccess 
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.8
    Type: AWS::Serverless::Function
    
  HelloWorldSF:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: arn:aws:iam::746167823857:role/stepfunctions-ex
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World example of the Amazon States Language using Pass states",
              "StartAt": "Hello",
              "States": {
                "Hello": {
                  "Type": "Task",
                  "Resource": "${helloArn}",
                  "Next": "World"
                },
                "World": {
                  "Type": "Task",
                  "Resource": "${worldArn}",
                  "End": true
                }
              }
            }
          - {helloArn: !GetAtt [ HelloFunction, Arn ], worldArn: !GetAtt [ WorldFunction, Arn ]}
