AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Timeout: 900
Outputs:
  Hello:
    Value: !GetAtt Hello.Arn
  World:
    Value: !GetAtt World.Arn
Resources:
  Hello:
    Properties:
      CodeUri: hello/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.8
    Type: AWS::Serverless::Function
  World:
    Properties:
      CodeUri: world/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
